# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'marknpark' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for marknpark
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'marknparkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
